---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# NHS-R Community Conference 2023
## Modelling non-linear data with Generalized Additive Models (GAMs), using the mgcv package
<!-- badges: start -->
<!-- badges: end -->

This is a repository for my workshop on GAMs for NHS-R community conference 2023.

This course uses Simon Wood's `mgcv` R package: https://cran.r-project.org/web/packages/mgcv/index.html

The teaching material draws heavily from Noam Ross' introduction to GAMs in R course, and you can find the course
and the GitHub repository on the following links:

https://noamross.github.io/gams-in-r-course/

https://github.com/noamross/gams-in-r-course

They are really good, and you'll find out more about GAMs using them than my workshop will cover.


The course material in this course is licensed CC-BY, meaning you are free to use it, change it etc. as long as you attribute the original workshop to me, and I in turn attribute the source material and inspiration to Noam Ross. 
You can view the slides at: https://chrismainey.github.io/whats_overdispersion/presentation.html
